
import java.awt.Color;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vmalonso
 */
public class ScoreBoard extends javax.swing.JPanel {

    private int score;
    private JLabel label;
    private int level;
    private JLabel labelLevel;
    private String user;
    private JLabel labelUser;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        score = 0;
        user = null;
        initComponents();
        label = new JLabel("Points: 0");
        add(label);
        labelLevel = new JLabel("Level: 0");
        add(labelLevel);
        labelUser = new JLabel ("User: ");
        add(labelUser);
    }

    
    public void resetScoreBoard() {
        score = 0;
        level = 0;
        label.setForeground(Color.black);
        label.setText("Pts: " + score);
        labelLevel.setText("Lv: " + level);
    }
    
    public void incrementScore() {
        score++;
        label.setText("Pts: " + score);
    }

    public void incrementScore(int points) {
        score += points;
        label.setText("Pts: " + score);
    }

    public int getScore() {
        return score;
    }
    
    public void incrementLevel(){
        level++;
        labelLevel.setText("Lv: " + level);
    }
    
    public int getLevel(){
        return level;
    }
    
    public String getName() {
        return user;
    }
    
    public void setName(String name){
        user = name;
        labelUser.setText(user);
    }

    public void setGameOver() {
        label.setText("GAME OVER. " + score + " points; Level: " + level);
        label.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
